export const SET_ACTIVE_TIMER = 'SET_ACTIVE_TIMER';
export const SET_PLAY_SOURCE = 'SET_PLAY_SOURCE';
export const SET_TIMERS = 'SET_TIMERS';
export const SET_TIMER_STATUS = 'SET_TIMER_STATUS';
export const UPDATE_TIMER_VALUE = 'UPDATE_TIMER_VALUE';
