export const SET_AUTOPLAY = 'SET_AUTOPLAY';
export const SET_CYCLE = 'SET_CYCLE';
export const SET_PLAY_CHIME = 'SET_PLAY_CHIME';
export const SET_CHIME = 'SET_CHIME';
export const SHOW_STATS_INTERRUPTIONS = 'SHOW_STATS_INTERRUPTIONS';
export const SET_STATS_WINDOW = 'SET_STATS_WINDOW';
